export interface Job {
    id: string;
    title: string;
    company: string;
    logo: string;
    location: string;
    type: 'Full-time' | 'Contract' | 'Freelance';
    level: 'Entry' | 'Mid' | 'Senior' | 'Lead';
    salary: string;
    tags: string[];
    postedAt: string;
    featured?: boolean;
}

export const JOBS: Job[] = [
    {
        id: '1',
        title: 'Senior Rust Developer',
        company: 'Mysten Labs',
        logo: '/images/partners/sui-logo.svg',
        location: 'Remote (US/EU)',
        type: 'Full-time',
        level: 'Senior',
        salary: '$140k - $220k',
        tags: ['Rust', 'Blockchain', 'Sui'],
        postedAt: '2 days ago',
        featured: true,
    },
    {
        id: '2',
        title: 'Smart Contract Engineer',
        company: 'Cetus Protocol',
        logo: '/images/partners/cetus.svg',
        location: 'Remote',
        type: 'Full-time',
        level: 'Mid',
        salary: '$80k - $150k',
        tags: ['Move', 'DeFi', 'Smart Contracts'],
        postedAt: '5 hours ago',
        featured: true,
    },
    {
        id: '3',
        title: 'Community Manager',
        company: 'Scallop',
        logo: '/images/partners/flowxfinance.svg',
        location: 'Lagos, Nigeria',
        type: 'Contract',
        level: 'Entry',
        salary: '$1.5k - $3k /mo',
        tags: ['Community', 'Social Media', 'Marketing'],
        postedAt: '1 day ago',
    },
    {
        id: '4',
        title: 'Frontend Developer (Next.js)',
        company: 'Bluefin',
        logo: '/images/partners/deepbook.svg',
        location: 'Remote',
        type: 'Full-time',
        level: 'Mid',
        salary: '$60k - $100k',
        tags: ['React', 'TypeScript', 'Web3'],
        postedAt: '3 days ago',
    },
    {
        id: '5',
        title: 'Product Designer',
        company: 'Sui Foundation',
        logo: '/images/partners/sui-logo.svg',
        location: 'Remote',
        type: 'Contract',
        level: 'Senior',
        salary: '$80 - $120 /hr',
        tags: ['UI/UX', 'Figma', 'Design System'],
        postedAt: '1 week ago',
        featured: true,
    },
    {
        id: '6',
        title: 'Developer Relations Engineer',
        company: 'Mysten Labs',
        logo: '/images/partners/sui-logo.svg',
        location: 'London, UK',
        type: 'Full-time',
        level: 'Senior',
        salary: '$120k - $180k',
        tags: ['DevRel', 'Content', 'Community'],
        postedAt: '4 days ago',
        featured: true,
    },
    {
        id: '7',
        title: 'Marketing Specialist',
        company: 'Typus Finance',
        logo: '/images/logos/sui-ng-logo.png',
        location: 'Remote',
        type: 'Contract',
        level: 'Entry',
        salary: '$2k - $4k /mo',
        tags: ['Marketing', 'Growth', 'Analytics'],
        postedAt: '6 hours ago',
    },
    {
        id: '8',
        title: 'Security Auditor',
        company: 'OtterSec',
        logo: '/images/logos/sui-ng-logo.png',
        location: 'Remote',
        type: 'Full-time',
        level: 'Senior',
        salary: '$200k - $350k',
        tags: ['Security', 'Auditing', 'Rust'],
        postedAt: '1 day ago',
    },
    {
        id: '9',
        title: 'Backend Engineer',
        company: 'Aftermath Finance',
        logo: '/images/partners/cetus.svg',
        location: 'Remote',
        type: 'Full-time',
        level: 'Mid',
        salary: '$90k - $140k',
        tags: ['Rust', 'TypeScript', 'DeFi'],
        postedAt: '2 days ago',
    },
    {
        id: '10',
        title: 'Technical Writer',
        company: 'Sui Foundation',
        logo: '/images/partners/sui-logo.svg',
        location: 'Remote',
        type: 'Contract',
        level: 'Mid',
        salary: '$50 - $80 /hr',
        tags: ['Content', 'Documentation', 'Web3'],
        postedAt: '5 days ago',
    },
    {
        id: '11',
        title: 'Full Stack Developer',
        company: 'Turbos Finance',
        logo: '/images/partners/flowxfinance.svg',
        location: 'Singapore',
        type: 'Full-time',
        level: 'Senior',
        salary: '$100k - $160k',
        tags: ['React', 'Move', 'TypeScript'],
        postedAt: '3 days ago',
    },
    {
        id: '12',
        title: 'NFT Artist',
        company: 'Clutchy',
        logo: '/images/logos/sui-ng-logo.png',
        location: 'Remote',
        type: 'Freelance',
        level: 'Mid',
        salary: '$3k - $10k /project',
        tags: ['Design', 'NFT', 'Creative'],
        postedAt: '1 week ago',
    },
    {
        id: '13',
        title: 'Protocol Engineer',
        company: 'NAVI Protocol',
        logo: '/images/partners/deepbook.svg',
        location: 'Remote',
        type: 'Full-time',
        level: 'Senior',
        salary: '$130k - $200k',
        tags: ['Move', 'DeFi', 'Blockchain'],
        postedAt: '4 days ago',
    },
    {
        id: '14',
        title: 'Growth Lead',
        company: 'Bucket Protocol',
        logo: '/images/partners/cetus.svg',
        location: 'Remote',
        type: 'Full-time',
        level: 'Lead',
        salary: '$100k - $150k',
        tags: ['Marketing', 'Growth', 'Strategy'],
        postedAt: '2 days ago',
    },
    {
        id: '15',
        title: 'QA Engineer',
        company: 'Cetus Protocol',
        logo: '/images/partners/cetus.svg',
        location: 'Remote',
        type: 'Full-time',
        level: 'Mid',
        salary: '$60k - $90k',
        tags: ['Testing', 'Automation', 'Web3'],
        postedAt: '6 days ago',
    },
    {
        id: '16',
        title: 'Data Analyst',
        company: 'Sui Foundation',
        logo: '/images/partners/sui-logo.svg',
        location: 'Remote',
        type: 'Contract',
        level: 'Mid',
        salary: '$70k - $100k',
        tags: ['Analytics', 'SQL', 'Python'],
        postedAt: '1 week ago',
    },
    {
        id: '17',
        title: 'Mobile Developer',
        company: 'Suiet Wallet',
        logo: '/images/partners/flowxfinance.svg',
        location: 'Remote',
        type: 'Full-time',
        level: 'Mid',
        salary: '$80k - $120k',
        tags: ['React Native', 'TypeScript', 'Mobile'],
        postedAt: '3 days ago',
    },
    {
        id: '18',
        title: 'Tokenomics Designer',
        company: 'Aftermath Finance',
        logo: '/images/partners/deepbook.svg',
        location: 'Remote',
        type: 'Contract',
        level: 'Senior',
        salary: '$100 - $150 /hr',
        tags: ['Tokenomics', 'DeFi', 'Economics'],
        postedAt: '5 days ago',
    },
];

export const FILTERS = {
    types: ['Full-time', 'Contract', 'Freelance', 'Internship'],
    levels: ['Entry Level', 'Mid Level', 'Senior Level', 'Lead', 'Executive'],
    categories: [
        'Video Editing',
        'Animation',
        'Software Development',
        'Product Design',
        'Ghost Writing',
        'Graphics Design',
        'Smart Contract Auditor',
        'Sui-Move Dev',
        'Product Manager',
        'Social Media Manager',
        'NFT Specialist',
        'Community Manager',
        'Quant/Tokenomics Expert',
        'Cyber Security',
    ],
    salary: ['$0 - $50k', '$50k - $100k', '$100k - $150k', '$150k+', 'Hourly'],
};
