import type { ForumPost, ForumComment } from '@/lib/forum-types';

export const mockPosts: ForumPost[] = [
  {
    id: 'post-1',
    title: 'How does Sui\'s object-centric model differ from Ethereum\'s account model?',
    body: 'I\'ve been reading about Sui\'s architecture and I keep seeing references to an "object-centric" model. Coming from Ethereum, I\'m used to thinking about state in terms of accounts and storage slots. Can someone break down the key differences and why Sui chose this approach?\n\nSpecifically, I\'m curious about:\n- How does ownership work for objects?\n- What are shared vs. owned objects?\n- How does this affect gas fees and parallelism?\n\nAny resources or explanations would be really helpful. Trying to understand the fundamentals before diving into Move development.',
    category: 'move',
    author_address: '0x7a16ff8270133f063af...b3d9e',
    vote_score: 47,
    comment_count: 8,
    created_at: '2026-02-14T18:30:00Z',
  },
  {
    id: 'post-2',
    title: 'Cetus vs. Turbos — which concentrated liquidity DEX do you prefer?',
    body: 'Both Cetus and Turbos offer concentrated liquidity on Sui. I\'ve been providing liquidity on both and noticed some differences in fee tiers, UI, and pool depth. Curious what the community thinks.\n\nCetus seems to have deeper liquidity and more trading pairs, but Turbos has a cleaner interface IMO. What\'s your experience?',
    category: 'defi',
    author_address: '0x3e8f1c2d4a5b6e7f8...9c0d1',
    vote_score: 32,
    comment_count: 14,
    created_at: '2026-02-14T14:15:00Z',
  },
  {
    id: 'post-3',
    title: 'Built my first NFT collection on Sui — here\'s what I learned',
    body: 'Just deployed a 1,000 piece generative art collection on Sui using Move. The experience was surprisingly smooth compared to Solidity. A few things that stood out:\n\n1. Display standard is great — metadata just works\n2. Kiosk framework is powerful but has a learning curve\n3. Gas costs were negligible even for batch mints\n4. The object model makes royalty enforcement much cleaner\n\nHappy to share my contract structure and deployment scripts if anyone is interested.',
    category: 'showcase',
    author_address: '0xab12cd34ef56...78901234',
    vote_score: 89,
    comment_count: 21,
    created_at: '2026-02-13T22:00:00Z',
  },
  {
    id: 'post-4',
    title: 'Getting "InsufficientGas" error when calling my Move function — help?',
    body: 'I\'m trying to call a Move function that creates a new shared object, but I keep getting InsufficientGas errors even with what seems like a high gas budget. My function takes a vector of ~50 elements and processes them in a loop.\n\nHere\'s the error:\n```\nInsufficientGas { cost: 52000000 }\n```\n\nIs there a way to estimate gas cost beforehand? Is there a limit on computation per transaction?',
    category: 'help',
    author_address: '0x5f6a7b8c9d0e...1f2a3b4c',
    vote_score: 15,
    comment_count: 6,
    created_at: '2026-02-14T09:45:00Z',
  },
  {
    id: 'post-5',
    title: 'Walrus storage deep dive — how erasure coding makes it work',
    body: 'I\'ve been exploring Walrus for hosting a dApp frontend and wanted to share my understanding of how the storage layer works.\n\nWalrus uses Reed-Solomon erasure coding to split data across multiple storage nodes. This means your data survives even if a significant portion of nodes go offline. The reconstruction threshold is configurable.\n\nFor a typical blob, the data is encoded into N shards where only K < N are needed to reconstruct. This gives you redundancy without the cost of full replication.\n\nThe economics are interesting too — storage is priced per epoch and you can extend it. Compare this to Arweave\'s perpetual storage model.',
    category: 'walrus',
    author_address: '0xde4f5a6b7c8d...9e0f1a2b',
    vote_score: 61,
    comment_count: 9,
    created_at: '2026-02-13T16:20:00Z',
  },
  {
    id: 'post-6',
    title: 'Sui Nigeria Meetup Lagos — February 2026 recap',
    body: 'Great turnout at the Lagos meetup last weekend! We had about 80 developers and builders show up. Highlights:\n\n- Workshop on Move smart contract basics\n- Panel discussion on DeFi opportunities in Nigeria\n- Live demo of building a token on Sui\n- Networking session with local Web3 founders\n\nNext meetup is planned for March. If you\'re in Lagos or Abuja, join the Telegram group for updates. We\'re also looking for speakers!',
    category: 'general',
    author_address: '0x1234abcd5678...ef901234',
    vote_score: 124,
    comment_count: 31,
    created_at: '2026-02-12T20:00:00Z',
  },
  {
    id: 'post-7',
    title: 'DeepBook CLOB — building a trading bot in Move',
    body: 'I\'ve been experimenting with building an on-chain market making bot that interacts directly with DeepBook. The CLOB architecture is really elegant — fully on-chain order book with price-time priority matching.\n\nMy bot places limit orders around the mid price and adjusts based on inventory. The tricky part is managing gas costs for frequent order updates. Has anyone found efficient patterns for this?',
    category: 'deepbook',
    author_address: '0x9a8b7c6d5e4f...3a2b1c0d',
    vote_score: 38,
    comment_count: 7,
    created_at: '2026-02-14T06:30:00Z',
  },
  {
    id: 'post-8',
    title: 'Is Seal protocol the future of access control on Sui?',
    body: 'Just read the Seal whitepaper and it\'s fascinating. Threshold encryption for on-chain access control opens up so many possibilities:\n\n- Token-gated content that\'s actually encrypted, not just hidden behind a check\n- Time-locked reveals for NFTs and governance\n- Subscription models where access is cryptographically enforced\n\nThe integration with Walrus for encrypted blob storage is particularly interesting. Thoughts on adoption potential?',
    category: 'seal',
    author_address: '0xf0e1d2c3b4a5...96877453',
    vote_score: 53,
    comment_count: 11,
    created_at: '2026-02-13T12:10:00Z',
  },
];

export const mockComments: ForumComment[] = [
  // Comments for post-1 (object-centric model)
  {
    id: 'c1',
    post_id: 'post-1',
    parent_id: null,
    body: 'Great question! The biggest difference is that in Sui, every piece of state is an "object" with a unique ID, an owner, and a type. Unlike Ethereum where state lives in contract storage slots, Sui objects are first-class citizens.\n\nOwned objects can only be used by their owner, which means transactions touching different owned objects can be processed in parallel — that\'s where Sui gets its speed.',
    author_address: '0xaa11bb22cc33...dd44ee55',
    vote_score: 23,
    depth: 0,
    created_at: '2026-02-14T19:00:00Z',
  },
  {
    id: 'c2',
    post_id: 'post-1',
    parent_id: 'c1',
    body: 'To add to this — shared objects are the ones that need consensus (like a DEX pool that many users interact with). Owned objects skip consensus entirely, which is why simple transfers are nearly instant.',
    author_address: '0x5566778899aa...bbccddee',
    vote_score: 15,
    depth: 1,
    created_at: '2026-02-14T19:20:00Z',
  },
  {
    id: 'c3',
    post_id: 'post-1',
    parent_id: 'c2',
    body: 'This is what makes Sui\'s gas model different too. Since owned object transactions don\'t need full consensus, they\'re cheaper. The gas price is determined by a reference gas price set by validators each epoch.',
    author_address: '0xffeeddccbbaa...99887766',
    vote_score: 8,
    depth: 2,
    created_at: '2026-02-14T19:45:00Z',
  },
  {
    id: 'c4',
    post_id: 'post-1',
    parent_id: 'c2',
    body: 'Exactly. And the cool thing is that Move\'s type system enforces ownership at the language level. You literally can\'t access an object you don\'t own — the compiler won\'t let you.',
    author_address: '0x1a2b3c4d5e6f...7a8b9c0d',
    vote_score: 11,
    depth: 2,
    created_at: '2026-02-14T20:10:00Z',
  },
  {
    id: 'c5',
    post_id: 'post-1',
    parent_id: null,
    body: 'I recommend reading the Sui documentation on "Object Model" — it has great diagrams. Also check out the Move Book, specifically the chapters on ownership and transfer policies.',
    author_address: '0xde4f5a6b7c8d...9e0f1a2b',
    vote_score: 19,
    depth: 0,
    created_at: '2026-02-14T19:30:00Z',
  },
  {
    id: 'c6',
    post_id: 'post-1',
    parent_id: 'c5',
    body: 'The Move Book is an amazing resource. Also worth checking out the "Sui in 6 Minutes" video from Mysten Labs for a high-level overview.',
    author_address: '0x3e8f1c2d4a5b...6e7f8901',
    vote_score: 7,
    depth: 1,
    created_at: '2026-02-14T20:00:00Z',
  },
  {
    id: 'c7',
    post_id: 'post-1',
    parent_id: null,
    body: 'One practical difference I noticed as a developer: in Ethereum, you update state by calling functions that modify storage. In Sui, you pass objects INTO functions, the function transforms them, and Move\'s linear type system ensures they go somewhere — you can\'t just drop them.',
    author_address: '0xab12cd34ef56...78901234',
    vote_score: 31,
    depth: 0,
    created_at: '2026-02-14T21:15:00Z',
  },
  {
    id: 'c8',
    post_id: 'post-1',
    parent_id: 'c7',
    body: 'This is a great way to explain it. The "objects flow through functions" mental model clicked for me when I started writing Move. It\'s like functional programming for on-chain state.',
    author_address: '0x7a16ff827013...3f063afb',
    vote_score: 14,
    depth: 1,
    created_at: '2026-02-14T21:40:00Z',
  },
  {
    id: 'c9',
    post_id: 'post-1',
    parent_id: 'c8',
    body: 'Exactly — and the compiler catches bugs at compile time that in Solidity would only show up as runtime exploits. Double-spend, reentrancy, unauthorized access — Move prevents all of these structurally.',
    author_address: '0x9a8b7c6d5e4f...3a2b1c0d',
    vote_score: 9,
    depth: 2,
    created_at: '2026-02-14T22:00:00Z',
  },
  {
    id: 'c10',
    post_id: 'post-1',
    parent_id: 'c9',
    body: 'No reentrancy vulnerabilities is such a massive win. That single issue has cost the EVM ecosystem billions.',
    author_address: '0xf0e1d2c3b4a5...96877453',
    vote_score: 6,
    depth: 3,
    created_at: '2026-02-14T22:20:00Z',
  },
  {
    id: 'c11',
    post_id: 'post-1',
    parent_id: 'c10',
    body: 'True, though it\'s worth noting that Move has its own class of bugs to watch for — like accidentally making objects shared when they should be owned, or forgetting to implement proper access control on admin functions.',
    author_address: '0xaa11bb22cc33...dd44ee55',
    vote_score: 4,
    depth: 4,
    created_at: '2026-02-14T22:35:00Z',
  },
  {
    id: 'c12',
    post_id: 'post-1',
    parent_id: null,
    body: 'Coming from Solana, I found Sui\'s object model much easier to reason about. Solana\'s account model is powerful but the manual serialization and account validation is tedious. Sui + Move handles so much of that for you.',
    author_address: '0x1234abcd5678...ef901234',
    vote_score: 17,
    depth: 0,
    created_at: '2026-02-15T01:00:00Z',
  },
  // Comments for post-3 (NFT collection showcase)
  {
    id: 'c13',
    post_id: 'post-3',
    parent_id: null,
    body: 'This is awesome! I\'ve been wanting to deploy an NFT collection on Sui but wasn\'t sure where to start. Would love to see your contract structure — especially how you handled the Kiosk integration for royalties.',
    author_address: '0x7a16ff827013...3f063afb',
    vote_score: 18,
    depth: 0,
    created_at: '2026-02-13T23:10:00Z',
  },
  {
    id: 'c14',
    post_id: 'post-3',
    parent_id: 'c13',
    body: 'Seconded! The Kiosk framework docs are a bit dense. A real-world example would be incredibly helpful for the community.',
    author_address: '0x5566778899aa...bbccddee',
    vote_score: 9,
    depth: 1,
    created_at: '2026-02-13T23:25:00Z',
  },
  {
    id: 'c15',
    post_id: 'post-3',
    parent_id: 'c13',
    body: 'I\'ll put together a GitHub repo this weekend with the full contract + deployment scripts. The key pattern is using a `Publisher` object to prove you\'re the creator, then setting up a `TransferPolicy` with your royalty rules.',
    author_address: '0xab12cd34ef56...78901234',
    vote_score: 24,
    depth: 1,
    created_at: '2026-02-14T00:05:00Z',
  },
  {
    id: 'c16',
    post_id: 'post-3',
    parent_id: null,
    body: 'How did you handle the generative art side? Did you do on-chain generation or off-chain with IPFS/Walrus for the images?',
    author_address: '0xde4f5a6b7c8d...9e0f1a2b',
    vote_score: 12,
    depth: 0,
    created_at: '2026-02-14T01:30:00Z',
  },
  {
    id: 'c17',
    post_id: 'post-3',
    parent_id: 'c16',
    body: 'I used Walrus for storing the images — works great and the cost is really low. The metadata is on-chain using the Display standard. Each NFT object has traits stored as dynamic fields.',
    author_address: '0xab12cd34ef56...78901234',
    vote_score: 15,
    depth: 1,
    created_at: '2026-02-14T02:00:00Z',
  },
  {
    id: 'c18',
    post_id: 'post-3',
    parent_id: 'c17',
    body: 'Dynamic fields for traits is really smart. That means you could potentially let holders upgrade or evolve their NFTs by modifying those fields, right?',
    author_address: '0x1234abcd5678...ef901234',
    vote_score: 8,
    depth: 2,
    created_at: '2026-02-14T03:15:00Z',
  },
  {
    id: 'c19',
    post_id: 'post-3',
    parent_id: null,
    body: 'Congrats on the launch! What marketplace are you listing on? Tradeport seems to have the most volume for Sui NFTs right now.',
    author_address: '0x3e8f1c2d4a5b...6e7f8901',
    vote_score: 7,
    depth: 0,
    created_at: '2026-02-14T08:00:00Z',
  },
  {
    id: 'c20',
    post_id: 'post-3',
    parent_id: 'c19',
    body: 'Tradeport and Clutchy both. Since Sui uses the Kiosk standard, your collection is automatically discoverable on any marketplace that supports it. No need to manually list on each one.',
    author_address: '0xab12cd34ef56...78901234',
    vote_score: 11,
    depth: 1,
    created_at: '2026-02-14T09:20:00Z',
  },
  {
    id: 'c21',
    post_id: 'post-3',
    parent_id: null,
    body: 'The gas costs comparison with Ethereum is insane. I spent ~$800 deploying a 10k collection on ETH last year. On Sui you could do it for cents. The future is here honestly.',
    author_address: '0x9a8b7c6d5e4f...3a2b1c0d',
    vote_score: 32,
    depth: 0,
    created_at: '2026-02-14T10:45:00Z',
  },
  {
    id: 'c22',
    post_id: 'post-3',
    parent_id: 'c21',
    body: 'And the parallelism means minting doesn\'t get bottlenecked. No more "gas wars" during mint events. Each user is minting their own owned object so it all processes in parallel.',
    author_address: '0xffeeddccbbaa...99887766',
    vote_score: 14,
    depth: 1,
    created_at: '2026-02-14T11:10:00Z',
  },
];
